import abtem
import matplotlib.pyplot as plt
import numpy as np

from sys import argv as call_arguments
from time import time
from datetime import datetime
from pathlib import Path
import logging
import sys

import xarray

# default settings
setup_analysis = {
    'scale':               'Hann',   # 'Hann' | '000' | 'Newton' | False
    'averaging_depth':     False,    # thickness-smoothing of intensities, depth in Å, e.g. 10.0
    'tolerance':           1e-6,     # ignore reflections with I < tolerance
    'g_max_limit':         2.0,      # ignore reflections with g_max > g_max_limit
    'bw_file':             None,     # set file name to call program without arguments
    'ms_file':             None,     # set file name to call program without arguments
    'save_images':         True      # if false, plots will be shown instead of exported (both png and pdf)
}
s = setup_analysis

#logger.info(abtem.__file__)
print(abtem.__file__)
#print(py3DED.__file__)


print('''
                         ad888888b,  88888888ba,    88888888888  88888888ba,    
                        d8"     "88  88      `"8b   88           88      `"8b   
                                a8P  88        `8b  88           88        `8b  
8b,dPPYba,   8b       d8     aad8"   88         88  88aaaaa      88         88  
88P'    "8a  `8b     d8'     ""Y8,   88         88  88"""""      88         88  
88       d8   `8b   d8'         "8b  88         8P  88           88         8P  
88b,   ,a8"    `8b,d8'  Y8,     a88  88      .a8P   88           88      .a8P   
88`YbbdP"'       Y88'    "Y888888P'  88888888Y"'    88888888888  88888888Y"'    
88               d8'                                                            
88              d8'

by Jacob Madsen, Małgorzata Katarzyna Cabaj, Paul Klar 
''') # https://patorjk.com/software/taag/#p=display&f=Univers&t=py3DED

#####
##### Input file as argument
#####

print(datetime.now().strftime('%Y%m%d-%H%M%S'))

# check program call
if len(call_arguments) == 2:
    # folder provided
    folder = Path( call_arguments[1] )
    file_ms = folder / "ms.zarr"
    file_bw = folder / "bw.zarr"
elif len(call_arguments) == 3:
    file_bw = Path( call_arguments[1] )
    file_ms = Path( call_arguments[2] )
else:
    file_bw = s['bw_file']
    file_ms = s['ms_file']
    if file_bw is not None and file_ms is not None:
        file_bw = Path( file_bw)
        file_ms = Path( file_ms)
    
# check files
if ( file_bw and file_ms and
     file_bw.exists() and file_ms.exists() and
     file_bw.name.endswith('.zarr') and file_ms.name.endswith('.zarr') ):
    s['bw_file'] = file_bw
    s['ms_file'] = file_ms
else:
    print('Problem identifying files!')
    print('BW:', file_bw)
    print('MS:', file_ms)
    print("""
    You can call the program in the following ways:
    
    (1) Default folder structure with bw.zarr and ms.zarr:
    python run_py3DED_analyse "path/to/folder_with_zarr_files"
    
    (2) Example call specifying output files of Bloch wave and multislice runs:
    python run_py3DED_analyse "path/to/bw_xyz.zarr" "path/to/ms_123.zarr"
    
    (3) If you update the dictionary setup_analysis ('bw_file', 'ms_file'),
        you can call the program without arguments.
    """)
    input(' ... press any key to exit ... ')
    
# all files generated by this program will be written to the folder of file_ms
export_base = Path( file_bw ).parent

# configure logging to console and logfile
def setup_logger(logfile: Path) -> logging.Logger:
    logger = logging.getLogger('py3ded_compare')
    logger.setLevel(logging.INFO)
    logger.propagate = False
    logger.handlers.clear()

    formatter = logging.Formatter('%(message)s')

    console_handler = logging.StreamHandler(sys.stdout)
    console_handler.setLevel(logging.INFO)
    console_handler.setFormatter(formatter)

    file_handler = logging.FileHandler(logfile, mode='w', encoding='utf-8')
    file_handler.setLevel(logging.INFO)
    file_handler.setFormatter(formatter)

    logger.addHandler(console_handler)
    logger.addHandler(file_handler)
    return logger


logfile = export_base / 'analyse.log'
logger = setup_logger(logfile)

logger.info(datetime.now().strftime('%Y%m%d-%H%M%S'))


def log(*args, sep=' ', end='\n'):
    message = sep.join(str(arg) for arg in args)
    if end != '\n':
        message += end.rstrip('\n')
    logger.info(message)


def sep():
    logger.info('- ' * 42)

logger.info(datetime.now().strftime('%Y%m%d-%H%M%S'))
sep()

# read data
logger.info(file_bw)
logger.info("Reading BW data ... ")
# abtem.from_zarr expects a str url (it calls .endswith(".zip") on it), not a Path
data_bw = abtem.from_zarr(str(file_bw)).to_data_array() #.compute()
logger.info("done.")
logger.info("")
logger.info(file_ms)
logger.info("Reading MS data ... ")
data_ms = abtem.from_zarr(str(file_ms)).to_data_array() #.compute()
logger.info("done.")
logger.info("")

# output folder
logger.info('Output folder:')
logger.info(export_base.resolve())

# figures
if s['save_images']:
    logger.info('Images will be saved.')

logger.info("")

# check basic data parameters
sep()
logger.info('Check match of xarray coordinates:')
align = False
for k in ('hkl', 'z', 'x_rotation'):
    logger.info(f'{k:>16} : ')
    if set(data_bw[k].data) == set(data_ms[k].data):
        logger.info(f'OK.   BW / MS: {len(data_bw[k]):6d} / {len(data_ms[k]):<6d}')
    else:
        logger.info(f'not OK !!!   BW / MS: {len(data_bw[k]):6d} / {len(data_ms[k]):6d}')
        align = True
        

if align:
    data_bw, data_ms = xarray.align( data_bw, data_ms, join="inner")
    print(data_bw.shape, data_ms.shape)
    
    

for data in (data_bw, data_ms):
    # check for duplicate hkl values
    if len(data['hkl'].data) != len(set(data['hkl'].data)):
        logger.info('!!! There are duplicate hkl indices.')

# filter out reflections via resolution filter
if s['g_max_limit'] and s['g_max_limit'] > 0:
    sep()
    logger.info('Resolution filter:')
    logger.info(f"gmax limit:                {s['g_max_limit']:.2f}")    

    N_hkl_old = len(data_bw['hkl'])
    
    data_bw = data_bw.sel(hkl=(data_bw['k']<s['g_max_limit']))
    data_ms = data_ms.sel(hkl=(data_ms['k']<s['g_max_limit']))

    N_hkl_new = len(data_bw['hkl'])

    if not np.all(data_bw['hkl'] == data_ms['hkl']):
        logger.info("!!! hkl indices of BW and MS are not identical!")
    
    logger.info(f'Reflections in data:       {N_hkl_old}')
    logger.info(f'Reflections filtered out:  {N_hkl_old - N_hkl_new}')
    logger.info(f'Reflections kept:          {N_hkl_new}')

sep()
# now things are faster when precomputing (decompressing?) the data    
logger.info("Loading data to memory ... ")
logger.info("BW ...")
data_bw = data_bw.compute()
logger.info("MS ...")
data_ms = data_ms.compute()

# filter out weakest reflections
if s['tolerance']:
    sep()
    logger.info('Intensity tolerance filter:')
    logger.info(f"Intensity threshold:       {s['tolerance']:.1E}")    
    
    # strongest intensity along alpha, averaged by z
    # peak value of each z-averaged rocking curve, use BW as reference
    max_bw = data_bw.mean(dim='z').max(dim='x_rotation') #.compute()
    hkl_mask = max_bw.data > s['tolerance']
    
    data_bw = data_bw.sel(hkl=hkl_mask)
    data_ms = data_ms.sel(hkl=hkl_mask)

    N_hkl_old = len(max_bw)
    N_hkl_new = np.count_nonzero(hkl_mask)
    
    logger.info(f'Reflections in data:       {N_hkl_old}')
    logger.info(f'Reflections filtered out:  {N_hkl_old - N_hkl_new}')
    logger.info(f'Reflections kept:          {N_hkl_new}')

# scale frames
if s['scale']:
    sep()
    logger.info(' ... scaling ... ')
    
    # numpy arrays
    dat1 = data_ms.data
    dat2 = data_bw.data

    N_x, N_z, N_hkl = dat1.shape
    
    logger.info("    SCALE                                 DEVIATION ** 2")
    logger.info('  #    min    max   mean  sigma           sum          mean       sigma       Nopt    step')

    # scales based on 000 and # initial differences squared
    s000 = (dat2[:,:,0] / dat1[:,:,0]).reshape(N_x, N_z, 1)  
    d000 = np.sum( (dat1*s000 - dat2)**2, axis=2 )   
    logger.info(f'    {s000.min():6.3f} {s000.max():6.3f} {s000.mean():6.3f} {s000.std():6.3f}    {d000.sum():10.4f}    {d000.mean():10.6f}  {d000.std():10.6f} {N_x*N_z:10d} based on 000')        
    
    # expected scales from Hann window and # initial differences squared
    s_hann = np.ones([N_x, N_z, 1]) * (8/3)**2
    d_hann = np.sum( (dat1*s_hann - dat2)**2, axis=2 )   
    logger.info(f'    {s_hann.min():6.3f} {s_hann.max():6.3f} {s_hann.mean():6.3f} {s_hann.std():6.3f}    {d_hann.sum():10.4f}    {d_hann.mean():10.6f}  {d_hann.std():10.6f} {N_x*N_z:10d} based on (8/3)**2')
    
    scale_factors = s_hann
    
    if s['scale'] == '000':
        #s000 = scale_factors = data_bw.sel(hkl='0 0 0') / data_ms.sel(hkl='0 0 0')
        logger.info('Scale factors based on intensity ratio of 000 from BW and MS.')
        scale_factors = s000
    elif s['scale'].lower() == 'hann':
        
        print('Expected scale factor from Hann window (8/3)**2:', (8/3)**2)        
        scale_factors = s_hann
    elif s['scale'] == 'Newton':
        # setup Newton
        step_factor = 0.4       # initial step factor, decreases if 
        step_factor_min = 0.04  # do not further decrease step factor
        change_tol = 0.5e-3       # target precision for scale changes
        start_tol = 1e-7        # skip scale optimisation for frames where the sum of squared deltas is less than this
        max_iterations = 500     # maximum number of iterations. 
        epsilon = 0.0001        # epsilon for simple numerical derivative

        # starting values for scales
        sn = s_hann
        
        # do not scale those frames where the deviation is already small
        mask000 = d000 > start_tol

        t0 = time()
        #print("    SCALE                                 DEVIATION ** 2")
        #print('  #    min    max   mean  sigma           sum          mean       sigma       Nopt    step')
        #print(f'    {s000.min():6.3f} {s000.max():6.3f} {s000.mean():6.3f} {s000.std():6.3f}    {d000.sum():10.4f}    {d000.mean():10.6f}  {d000.std():10.6f} {N_x*N_z:10d} based on 000')
        
        # optimise scales
        for i in range(1, max_iterations+1):
            # run Newton
            dn = np.sum( (dat1*sn - dat2)**2, axis=2 )
            d1 = np.sum( (dat1*(sn - epsilon/2) - dat2)**2, axis=2 )
            d2 = np.sum( (dat1*(sn + epsilon/2) - dat2)**2, axis=2 )
            
            m = (d1 - d2) / epsilon
            
            mask = np.abs(m) > change_tol
            mask = mask & mask000
            
            # testing....
            #if i < 10:
            #    step_factor = 0.05
            #elif i == 11:
            #    step_factor = 0.2
                
            scale_change = step_factor * dn / m
        
            N_update = np.count_nonzero(mask)
        
            logger.info(f'{i:3d} {sn.min():6.3f} {sn.max():6.3f} {sn.mean():6.3f} {sn.std():6.3f}    {dn.sum():10.4f}    {dn.mean():10.6f}  {dn.std():10.6f} {N_update:10}   {step_factor:.3f}')
    
            # update step factor
            if i%10 == 0 and step_factor > step_factor_min:
                step_factor *= 0.6
    
            # finish optimisation if no further scales are updated
            if N_update == 0:
                break
        
            sn[mask] += scale_change.reshape(N_x,N_z,1)[mask]
            
            # make sure scales are positive
            sn = np.abs(sn)

        scale_factors = sn
        logger.info(f'DONE. {time()-t0:.1f} seconds')

        # scale factors determined
        logger.info('Scale factors determined by minimising squared differences based on simple Newton method.')  
        
    logger.info('Applying scale factors to MS data.')

    #apply scale factors
    data_ms *= scale_factors

    ###
    ### plot scale factors
    ###
    
    xrange = data_bw['z'][[0,-1]].data
    yrange = data_bw['x_rotation'][[0,-1]].data*180/np.pi
    aspect = abs( (xrange[1] - xrange[0]) / (yrange[1] - yrange[0]) )
    if not (0.1 < aspect < 10):
        extent = [*xrange, *yrange ] # xlim0, xlim1, ylim0, ylim1
        
        fig_scale_factors, ax = plt.subplots()

        tmp = ax.imshow(scale_factors, 
                   origin='lower',
                   aspect=aspect,
                   extent=extent,
                   cmap='viridis')
        ax.set_title("scale factors, frame-by-frame, incl. 000")
        ax.set_xlabel('z (Å)')
        ax.set_ylabel('rotation α (°)')
        fig_scale_factors.colorbar(tmp, fraction=0.04)
        
        if s['save_images']:
            fig_scale_factors.savefig(export_base / 'scale_factors.pdf', format='pdf', dpi=300)
            fig_scale_factors.savefig(export_base / 'scale_factors.png', format='png', dpi=300)
        else:
            plt.show()

# z averaging
if s['averaging_depth']:
    sep()
    logger.info('z-smoothing of intensities')
    # calculate rolling average of intensities considering intensities
    # from neighbouring thicknesses
    dz = ( data_bw.z[1] - data_bw.z[0] ).data

    # Determine number of values to be averaged
    N_averaging_window = int( s['averaging_depth'] / dz )

    # average intensities
    data_bw = data_bw.rolling(z=N_averaging_window).mean()
    data_ms = data_ms.rolling(z=N_averaging_window).mean()

    # remove first thickness coordinates
    data_bw = data_bw.isel(z=slice(N_averaging_window-1, None))
    data_ms = data_ms.isel(z=slice(N_averaging_window-1, None))

    logger.info('Intensities were z-smoothed.')
    print(N_averaging_window, 'values were used for a rolling average.')
    print('The first', N_averaging_window - 1, 'z coordinates were removed.')

sep()
logger.info('Coordinates in final data sets:')
logger.info('Dimension           N          1st           Last')
for dim, N, f, unit in zip(data_bw.dims, data_bw.shape, (">12.4f", ">12.1f", ">12"), ("rad", "Å", "")):
    logger.info(f'{dim:12} {N:8} {data_bw[dim].data[0]:{f}}   {data_bw[dim].data[-1]:{f}}   {unit}')

N_x, N_z, N_hkl = data_bw.shape

# integrated intensities
# consider applying Sg limit to reduce noise added to intensities?
int_bw = data_bw.sum(dim='x_rotation')
int_ms = data_ms.sum(dim='x_rotation')

#
### basic agreement
#
sep()
# integrated and scattered intensity
logger.info("Integrated intensity at last z:")
for label, data in zip(('BW','MS'),(int_bw, int_ms)):
    integrated_intensity = float(data.isel(z=-1).sum(dim='hkl') / N_x )
    logger.info(f"{label} {integrated_intensity:8.2%}")
logger.info("\n")

logger.info("Scattered intensity at last z:")
for label, data in zip(('BW','MS'),(int_bw, int_ms)):
    scattered_intensity = float(data.isel(z=-1).drop_sel(hkl='0 0 0').sum(dim='hkl') / N_x ) 
    logger.info(f"{label} {scattered_intensity:8.2%}")
logger.info("\n")  

sep()

# Bragg R factors of individual diffraction patterns (1 R per z and orientation)
delta = np.abs(data_bw - data_ms)
R_frames = 100 * delta.drop_sel(hkl='0 0 0').sum(dim='hkl') / data_bw.drop_sel(hkl='0 0 0').sum(dim='hkl') # 2D array of shape (N_x, N_z)

# Bragg R factor based on intensities, 1 R factor per thickness
delta = np.abs(int_bw - int_ms)
R_Bragg = 100 * delta.drop_sel(hkl='0 0 0').sum(dim='hkl') / int_bw.drop_sel(hkl='0 0 0').sum(dim='hkl')

# R factor based on amplitudes, 1 R factor per thickness
delta = np.abs(np.sqrt(int_bw) - np.sqrt(int_ms))
R = 100 * delta.drop_sel(hkl='0 0 0').sum(dim='hkl') / (np.sqrt(int_bw.drop_sel(hkl='0 0 0'))).sum(dim='hkl')


zmin = 20

# Bragg R_z_alpha
R_zmin =  R_frames.sel(z=R_frames['z'] > zmin).data.max()
logger.info("R Bragg factor of single frames: Bragg_R_z_alpha.csv")
logger.info("  Mean  Sigma    min    max(z>20)   max(all)")
logger.info(f"{R_frames.mean():6.3f} {R_frames.std():6.3f} {R_frames.min():6.3f} {R_zmin:6.2f}      {R_frames.max():6.2f} ")

# Bragg R_z
R_zmin =  R_Bragg.sel(z=R_Bragg['z'] > zmin).data.max()
logger.info("R Bragg factor of integrated intensities: Bragg_R_z.csv")
logger.info("  Mean  Sigma    min    max(z>20)   max(all)")
logger.info(f"{R_Bragg.mean():6.3f} {R_Bragg.std():6.3f} {R_Bragg.min():6.3f} {R_zmin:6.2f}      {R_Bragg.max():6.2f} ")

# not used in manuscript: R_z with amplitudes
R_zmin =  R.sel(z=R['z'] > zmin).data.max()
logger.info("R factor based on integrated amplitudes: Amplitudes_R_integrated.csv")
logger.info("  Mean  Sigma    min    max(z>20)   max(all)")
logger.info(f"{R.mean():6.2f} {R.std():6.2f} {R.min():6.2f} {R_zmin:6.2f}      {R.max():6.2f} ")


########################## CSV
# export to csv

# Bragg R_z_alpha
x_rotation_degrees = R_frames['x_rotation'] * 180/np.pi
R_frames_export = R_frames.to_pandas().set_index(x_rotation_degrees.to_index())
R_frames_export.to_csv(export_base / 'Bragg_R_z_alpha.csv', index_label=' alpha', float_format="{0:6.2f}".format)

# Bragg R_z
R_Bragg.to_pandas().to_csv( export_base / 'Bragg_R_z.csv',
                            header=['Bragg_R_z(%)'])
                            
# amplitudes R_z
R.to_pandas().to_csv( export_base / 'Amplitudes_R_integrated.csv',
                      header=['R_integrated_amplitudes(%)'])



sep()

logger.info(datetime.now().strftime('%Y%m%d-%H%M%S'))

# close logfile
#
##### PLOTS
#

#
### total_intensity.png: Total integrated intensity including 000   +   scattered intensity excl. 000
#

fig_total_I, ax = plt.subplots(ncols=2, figsize=(12,5))

for data in (int_bw, int_ms):
    ax[0].plot( data['z'], 100 * (data.sum(dim='hkl') / N_x ) )
    ax[0].set_ylabel("total integrated intensity (%)")
    ax[0].set_title('Integrated intensity (incl. 000)')

for data in (int_bw, int_ms):
    ax[1].plot( data['z'], 100 * (data.drop_sel(hkl='0 0 0').sum(dim='hkl') / N_x ) )
    ax[1].set_ylabel("total scattered intensity (%)")
    ax[1].set_title('Scattered intensity (excl. 000)')

for i in (0,1):
    ax[i].set_xlabel("thickness (Å)")
    ax[i].legend(['BW', 'MS'])

if s['save_images']:
    fig_total_I.savefig(export_base / 'total_intensity.pdf', format='pdf', dpi=300)
    fig_total_I.savefig(export_base / 'total_intensity.png', format='png', dpi=300)
else:
    plt.show()


###
### R_z: Bragg R factors based on integrated intensities as function of z
###

fig_R, ax = plt.subplots()
ax.plot( int_bw['z'], R_Bragg, label='$R_z$')
#ax.plot( int_bw['z'], R, '--', label='R[sqrt(I)]')
ax.set_xlabel('thickness (Å)')
ax.set_ylabel('$R_z$ (%)')
#ax.set_title('R factor (%), integrated intensities, excl. 000')
#ax.legend()
#ax.set_ylim(bottom=0.0)
ax.set_ylim(0.0, 4.0) # changed 10 May 2025

if s['save_images']:
    fig_R.savefig(export_base / 'R_z.pdf', format='pdf', dpi=300)
    fig_R.savefig(export_base / 'R_z.png', format='png', dpi=300)
else:
    plt.show()


###
### R_z_alpha: frame-by-frame Bragg R factors based on intensities as function of z and alpha
###

xrange = R_frames['z'][[0,-1]].data
yrange = R_frames['x_rotation'][[0,-1]].data*180/np.pi
aspect = abs( (xrange[1] - xrange[0]) / (yrange[1] - yrange[0]) )
extent = [*xrange, *yrange ] # xlim0, xlim1, ylim0, ylim1

fig_R_frames, ax = plt.subplots()

tmp = ax.imshow(R_frames, 
           origin='lower',
           aspect=aspect,
           extent=[*R_frames['z'][[0,-1]].data, 
                   *R_frames['x_rotation'][[0,-1]].data*180/np.pi],
           vmin=0.0, 
           vmax=10.0,
           cmap='viridis')
#ax.set_title("Bragg R factor (%), frame-by-frame, excl. 000")
ax.set_xlabel('thickness (Å)')
ax.set_ylabel('rotation $\\alpha$ (°)')
fig_R_frames.colorbar(tmp, fraction=0.04)

if s['save_images']:
    fig_R_frames.savefig(export_base / 'R_z_alpha.pdf', format='pdf', dpi=300)
    fig_R_frames.savefig(export_base / 'R_z_alpha.png', format='png', dpi=300)
else:
    plt.show()

fig_R_angle, ax = plt.subplots(figsize=(12,5))

###
### R_z_alpha as f(alpha): z-dependent and z-averaged R as function of rotation angle 
###

# z-averaged R
intz_bw = data_bw.mean(dim='z')
intz_ms = data_ms.mean(dim='z')

delta = np.abs(intz_bw - intz_ms)

# AVERAGE
Rz_Bragg = 100 * delta.drop_sel(hkl='0 0 0').sum(dim='hkl') / intz_bw.drop_sel(hkl='0 0 0').sum(dim='hkl')
ax.plot( Rz_Bragg['x_rotation']*180/np.pi, Rz_Bragg, '--', linewidth=3, label=f"z-averaged")

# frame-by-frame R for a given z
for i in range(2, N_z-6, int(N_z/3)):
    ax.plot( R_frames['x_rotation']*180/np.pi, R_frames.isel(z=i), label=f"z = {R_frames['z'].isel(z=i).data:.0f} Å")
i = -1
ax.plot( R_frames['x_rotation']*180/np.pi, R_frames.isel(z=i), linewidth=1, label=f"z = {R_frames['z'].isel(z=i).data:.0f} Å")
   
ax.set_xlabel('rotation $\\alpha$ (°)')
ax.set_ylabel('$R_{z,\\alpha}$ (%)')
#ax.set_title('Bragg R factor (%), frame-by-frame, excl. 000')
ax.legend()
ax.set_yscale('log')
ax.set_ylim(0.1,30.0)

if s['save_images']:
    fig_R_angle.savefig(export_base / 'R_z_alpha_angle.pdf', format='pdf', dpi=300)
    fig_R_angle.savefig(export_base / 'R_z_alpha_angle.png', format='png', dpi=300)
else:
    plt.show()

#
### Rocking curves
#

#
# determine hkl indices sorted by intensity, BW reference
#

# determine hkl indices of reflections to cover full intensity range from strongest to weakest
sort_by_intensity = np.argsort(int_bw.sum(dim='z').data)[::-1]
hkl_selection = sort_by_intensity[range(0,N_hkl, int(N_hkl/21))][:20]
hkl_selection[1] = sort_by_intensity[1] # strongest reflection that is not 000
hkl_selection[-1] = sort_by_intensity[-1] # weakest reflection

# min. number of points of rocking curve to show
minimum_range_to_show = 8.0   # degrees
angle_step = data_bw['x_rotation'][1] - data_bw['x_rotation'][0]
min_points = int( minimum_range_to_show / (angle_step.data * 180/np.pi) )

for z_id in (2, 10, N_z // 2, -1):
    this_t = R_frames['z'].isel(z=z_id).data
    
    fig_RCs, axes = plt.subplots(ncols=4, nrows=5, figsize=(12,18)) # 20 plots, sharex=True,

    for i, ax in enumerate(axes.ravel()):
        index = hkl_selection[i]
        reflection_hkl = str(data_bw['hkl'][index].data)

        # relevant alpha range with I > 0.02 * max(I)
        rocking_curve = data_bw.isel(z=z_id, hkl=index)
        angle_selection = (rocking_curve > (data_bw.isel(z=z_id, hkl=index).max().data * 0.02)).data
        significant_indices = np.argwhere( angle_selection ).flatten()
        first = significant_indices.min()
        last =  significant_indices.max()
        N_points = last - first
        if N_points >= min_points:
            selection = slice(first,last+1)
        else:
            first -= (min_points-N_points)//2
            last +=  (min_points-N_points)//2
            first = max(0,first)
            last = min(last, N_x-1)
            selection = slice(first,last+1)

        # plot
        ax.plot(data_bw['x_rotation'][selection]*180/np.pi, data_bw.isel(z=z_id, hkl=index).data[selection], label='BW '+reflection_hkl)
        ax.plot(data_ms['x_rotation'][selection]*180/np.pi, data_ms.isel(z=z_id, hkl=index).data[selection], '--', label='MS '+reflection_hkl)
        #ax.set_xlabel('rotation α (°)')
        #ax.set_ylabel('intensity')
        ax.ticklabel_format(style='sci', scilimits=(0,0), axis='y')
        ax.legend()
    fig_RCs.suptitle(f"intensity as function of rotation angle α (°), z = {data_bw['z'][z_id]:04.0f}Å")
    fig_RCs.tight_layout()

    if s['save_images']:
        name = f"rocking_curves_{this_t:.0f}"
        fig_RCs.savefig(export_base / (name+'.pdf'), format='pdf', dpi=300)
        fig_RCs.savefig(export_base / (name+'.png'), format='png', dpi=300)
    else:
        plt.show()
       
